[workspace]
channels = ["conda-forge"]
name = "votenet"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
matplotlib = '*'

plyfile = '*'
trimesh= '*'
networkx= '*'
scipy = "*"
pyvista = '*'

[pypi-dependencies]
opencv-python = '*'

[feature.gpu.system-requirements]
cuda = "12.0"

[feature.gpu.dependencies]
cuda-version = "12.6.*"
pytorch-gpu = "2.7.*"
cuda-toolkit = "12.*"
gxx = "*"
# [feature.gpu.pypi-dependencies]
# pointnet2 = { path = "pointnet2/", editable = true }



[feature.cpu.dependencies]
pytorch-cpu = "*"

[feature.test.dependencies]
pytest="*"

[environments]
cpu = ["cpu"]
default = ["gpu"]

# pointnet2 = {features = ["pointnet2"], solve-group = "gpu"}
test = {features = ["test"], solve-group = "gpu"}